### ISSUE TITLE
More detailed installation instructions

### ISSUE THREAD

**Issue by kellyrowland** [ryanstwrt/FRIDGe#2]
The "Install" header in the README includes a functional command for how to download the repository, but there are no further instructions for actual package installation (e.g., `python setup.py install`).

**Comment by ryanstwrt** [comment]
I've updated the README file to include a python setup step. Sorry about that, I totally blanked on add this to the README. Let me know if you think anything else should be added, other wise I will close this issue.

**Comment by kellyrowland** [comment]
Could you add an `install_requires` to `setup.py`? I tested the posted commands in a fresh Python 3 conda environment and got the following error:

```
Finished processing dependencies for FRIDGe==1.0.0
(fridge) rowlandk@DOE7603056:~/misc/FRIDGe(master)$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fridge.driver.fridge_driver as fd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rowlandk/misc/FRIDGe/fridge/driver/fridge_driver.py", line 1, in <module>
    import fridge.driver.global_variables as gb
  File "/Users/rowlandk/misc/FRIDGe/fridge/driver/global_variables.py", line 3, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
>>> 
```

Executing `pip install -r requirements.txt` in the directory resolved this; it would be good to have as part of the installation.

**Comment by ryanstwrt** [comment]
I apologize for the length of time it took me to get back to you! I've added the both the `install_requires` to my `setup.py` and `pip install -r requirements.txt` to my `readme.md`.

**Comment by kellyrowland** [comment]
No worries! Thanks very much for working through these requests. An installation in a clean conda environment works when following the posted instructions, so I'll close this out.
