### ISSUE TITLE
Minor paper edits

### ISSUE THREAD

**Issue by kellyrowland** [ryanstwrt/FRIDGe#3]
List of minor edits (grammar, capitalization, etc.) to be addressed in `paper.md`:

- [x] "to build full scale reactors cores" should be changed to "to build full scale reactor cores"
- [x] Change "experimental facilities, and increase" to "experimental facilities and the increase"
- [x] "given the users ability" should be "given the user's ability"
- [x] "The only inputes" should be "The only inputs"
- [x] Fix YAML citation (paper source has `[YAML]` rather than `[@YAML]`)
- [x] Change "plan view of the assembly" to "plane view of the assembly"

This may be a bug in the rendering - the Generation IV citation doesn't appear to be correctly capitalized in the draft PDF. I do see that you have the curly braces in the `.bib` file, so maybe that's out of your control? Would be good to fix if possible, but totally understandable if not.

**Comment by ryanstwrt** [comment]
Thanks for the edits! I'll address them here in the next couple of days. I'll investigate the Generation IV capitalization problem as well and see what can be done.

**Comment by ryanstwrt** [comment]
I've updated the paper with your edits and I've got Gen IV capitalization thing figured out.

**Comment by kellyrowland** [comment]
Awesome, thanks! Apologies for the delay in responding... vacation, etc. 😬
