### ISSUE TITLE
Supported Python Versions

### ISSUE THREAD

**Issue by pshriwise** [ryanstwrt/FRIDGe#4]
So I'm having success running the tests using Python 3.6.*, but for Python 3.5.* I'm seeing failures. Any thoughts on why that might be? I can attach the resulting MCNP input files from 3.5.2 if that would be helpful at all.

**Comment by ryanstwrt** [comment]
I'm not 100% sure why, I built FRIDGe using Python 3.6, so perhaps I need to be a bit more specific in my python requirements. However, it would be nice to be able to utilize other versions of Python 3. Would you mind sending me the MCNP input files and I'll take a look.

**Comment by pshriwise** [comment]
Looking at it more closely now. I think it's a key ordering issue. Starting with Python 3.6, keys maintain their order in dictionaries https://docs.python.org/3.6/whatsnew/3.6.html#new-dict-implementation.

So either switching to a `collections.OrderedDict` or replacing the built-in `dict` with `OrderedDict` for Python < 3.6 might do the trick.


[Fuel_Assembly_Test.txt](https://github.com/ryanstwrt/FRIDGe/files/3291676/Fuel_Assembly_Test.txt)

**Comment by ryanstwrt** [comment]
Thank you for the information. I believe I just took for granted Python 3.6's key ordering. I'll look into the best way to update this and get back to you.

**Comment by ryanstwrt** [comment]
@pshriwise I am thinking of requiring FRIDGe to be run using only Python 3.6 or greater instead of updating the dictionary types. I imagine there will be additional failures if I were to attempt to use a Python version between 3.0 and 3.5. Would this be acceptable?

**Comment by pshriwise** [comment]
Totally up to you! Personally, I think I'd do the same as 3.5 is kind of considered "on its way out" at this point. Either way, I'd only request that the Python versions you support are clarified in the documentation for the project.

**Comment by ryanstwrt** [comment]
Perfect. I've updated the documentation (README and github page) and the `setup.py` file to require Python 3.6 or later.
